local component = require("component")
local term = require("term")
local computer = require("computer")
local k = require("keyboard")
local shell = require("shell")

local g = component.gpu

print("Hello user! Searching for updates..")
os.sleep(1)
shell.execute("cd /home")
shell.execute("del fs-gui.luaDISABLED")
print("--Deleted FS-Gui--")
shell.execute("del startup.luaDISABLED")
print("--Deleted Startup--")
shell.execute("wget https://github.com/superjaja05/nc-fusion/blob/main/fs-gui.luaDISABLED")
print("--Downloaded latest FS-Gui--")
shell.execute("wget https://github.com/superjaja05/nc-fusion/blob/main/startup.luaDISABLED")
print("--Downloaded latest Startup--")
print("<<<Now starting program..>>>")
os.sleep(1)
shell.execute("fs-gui.lua")